
package com.company.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
// example 111-5
@WebServiceClient(name = "WebSvcRpcSampleImplService", targetNamespace = "http://company.com/", wsdlLocation = "http://localhost:9999/ws/websvcrpcsample?wsdl")
public class WebSvcRpcSampleImplService
    extends Service
{

    private final static URL WEBSVCRPCSAMPLEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSVCRPCSAMPLEIMPLSERVICE_EXCEPTION;
    private final static QName WEBSVCRPCSAMPLEIMPLSERVICE_QNAME = new QName("http://company.com/", "WebSvcRpcSampleImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/websvcrpcsample?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSVCRPCSAMPLEIMPLSERVICE_WSDL_LOCATION = url;
        WEBSVCRPCSAMPLEIMPLSERVICE_EXCEPTION = e;
    }

    public WebSvcRpcSampleImplService() {
        super(__getWsdlLocation(), WEBSVCRPCSAMPLEIMPLSERVICE_QNAME);
    }

    public WebSvcRpcSampleImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSVCRPCSAMPLEIMPLSERVICE_QNAME, features);
    }

    public WebSvcRpcSampleImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSVCRPCSAMPLEIMPLSERVICE_QNAME);
    }

    public WebSvcRpcSampleImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSVCRPCSAMPLEIMPLSERVICE_QNAME, features);
    }

    public WebSvcRpcSampleImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebSvcRpcSampleImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebSvcRpcSample
     */
    @WebEndpoint(name = "WebSvcRpcSampleImplPort")
    public WebSvcRpcSample getWebSvcRpcSampleImplPort() {
        return super.getPort(new QName("http://company.com/", "WebSvcRpcSampleImplPort"), WebSvcRpcSample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebSvcRpcSample
     */
    @WebEndpoint(name = "WebSvcRpcSampleImplPort")
    public WebSvcRpcSample getWebSvcRpcSampleImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://company.com/", "WebSvcRpcSampleImplPort"), WebSvcRpcSample.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSVCRPCSAMPLEIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSVCRPCSAMPLEIMPLSERVICE_EXCEPTION;
        }
        return WEBSVCRPCSAMPLEIMPLSERVICE_WSDL_LOCATION;
    }

}
